[package]
name = "tz-rs-fuzz"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
libfuzzer-sys = "0.4"
tz-rs = { path = "..", package = "tz-rs" }

[package.metadata]
cargo-fuzz = true

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"
test = false
doc = false
